name: minheap - Compile and Test

on:
  pull_request:
  push:
    branches:
      - master

env:
  # For headless DragonRuby execution
  SDL_AUDIODRIVER: dummy
  SDL_VIDEODRIVER: dummy

jobs:
  compile-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: kfischer-okarin/download-dragonruby@v1
        with:
          license_tier: pro
      - name: Apply patches
        run: |
          patch ./include/dragonruby.h include-patches.h.patch
          patch ./include/dragonruby.h.inc include-patches.inc.patch
      - uses: actions/upload-artifact@v3
        with:
          name: resulting-dragonruby-headers
          path: |
            ./include/dragonruby.h
            ./include/dragonruby.h.inc
      - name: Compile
        run: |
          clang --version
          clang ./minheap.c -g -O2 -std=c2x -I./include -fpic -shared -o native/linux-amd64/libminheap.so
